//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualizationService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string regionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                if ((object.ReferenceEquals(this.regionField, value) != true)) {
                    this.regionField = value;
                    this.RaisePropertyChanged("region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string skin {
            get {
                return this.skinField;
            }
            set {
                if ((object.ReferenceEquals(this.skinField, value) != true)) {
                    this.skinField = value;
                    this.RaisePropertyChanged("skin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.GameVisualizationServiceSoap")]
    public interface GameVisualizationServiceSoap {
        
        // CODEGEN: Generating message contract since element name listajugadoresResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listajugadores", ReplyAction="*")]
        VisualizationService.ServiceReference1.listajugadoresResponse listajugadores(VisualizationService.ServiceReference1.listajugadoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listajugadores", ReplyAction="*")]
        System.Threading.Tasks.Task<VisualizationService.ServiceReference1.listajugadoresResponse> listajugadoresAsync(VisualizationService.ServiceReference1.listajugadoresRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listajugadoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listajugadores", Namespace="http://tempuri.org/", Order=0)]
        public VisualizationService.ServiceReference1.listajugadoresRequestBody Body;
        
        public listajugadoresRequest() {
        }
        
        public listajugadoresRequest(VisualizationService.ServiceReference1.listajugadoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listajugadoresRequestBody {
        
        public listajugadoresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listajugadoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listajugadoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public VisualizationService.ServiceReference1.listajugadoresResponseBody Body;
        
        public listajugadoresResponse() {
        }
        
        public listajugadoresResponse(VisualizationService.ServiceReference1.listajugadoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listajugadoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VisualizationService.ServiceReference1.Player[] listajugadoresResult;
        
        public listajugadoresResponseBody() {
        }
        
        public listajugadoresResponseBody(VisualizationService.ServiceReference1.Player[] listajugadoresResult) {
            this.listajugadoresResult = listajugadoresResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GameVisualizationServiceSoapChannel : VisualizationService.ServiceReference1.GameVisualizationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameVisualizationServiceSoapClient : System.ServiceModel.ClientBase<VisualizationService.ServiceReference1.GameVisualizationServiceSoap>, VisualizationService.ServiceReference1.GameVisualizationServiceSoap {
        
        public GameVisualizationServiceSoapClient() {
        }
        
        public GameVisualizationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameVisualizationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameVisualizationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameVisualizationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VisualizationService.ServiceReference1.listajugadoresResponse VisualizationService.ServiceReference1.GameVisualizationServiceSoap.listajugadores(VisualizationService.ServiceReference1.listajugadoresRequest request) {
            return base.Channel.listajugadores(request);
        }
        
        public VisualizationService.ServiceReference1.Player[] listajugadores() {
            VisualizationService.ServiceReference1.listajugadoresRequest inValue = new VisualizationService.ServiceReference1.listajugadoresRequest();
            inValue.Body = new VisualizationService.ServiceReference1.listajugadoresRequestBody();
            VisualizationService.ServiceReference1.listajugadoresResponse retVal = ((VisualizationService.ServiceReference1.GameVisualizationServiceSoap)(this)).listajugadores(inValue);
            return retVal.Body.listajugadoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisualizationService.ServiceReference1.listajugadoresResponse> VisualizationService.ServiceReference1.GameVisualizationServiceSoap.listajugadoresAsync(VisualizationService.ServiceReference1.listajugadoresRequest request) {
            return base.Channel.listajugadoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisualizationService.ServiceReference1.listajugadoresResponse> listajugadoresAsync() {
            VisualizationService.ServiceReference1.listajugadoresRequest inValue = new VisualizationService.ServiceReference1.listajugadoresRequest();
            inValue.Body = new VisualizationService.ServiceReference1.listajugadoresRequestBody();
            return ((VisualizationService.ServiceReference1.GameVisualizationServiceSoap)(this)).listajugadoresAsync(inValue);
        }
    }
}
